version: '3'
services:
  centos7:
    container_name: "centos7"
    build: ./
    tty: true
    privileged: true
    command: /sbin/init   
    ports:
      - "2222:22"
      - "2080:80"
    volumes:
      - ./docker_data:/root/docker_data

    